# -*- coding: utf-8 -*-
"""testcase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gCYmxD9E9DbLFhPQ_fUuFBqkJY9JcyLU
"""

from google.colab import files

files.upload()

import project
from project import Cashier

# intance class untuk test case
trnsct_123 = Cashier()

# test case 1
trnsct_123.add_item("Ayam Goreng", 2,20000)
trnsct_123.add_item("Pasta Gigi", 3,15000)
print(f'Item yang dibeli adalah : {trnsct_123.transaction}')

# test case 2
trnsct_123.delete_item('Pasta Gigi')
print(f'Item yang dibeli adalah : {trnsct_123.transaction}')

# test case 3
trnsct_123.reset_transaction()

# test case 4
trnsct_123.add_item('Ayam Goreng',2,20000)
trnsct_123.add_item('Pasta Gigi',3,15000)
trnsct_123.add_item('Mainan mobil',1, 200000)
trnsct_123.add_item('Mie instan',5, 3000)
print(trnsct_123.transaction)
print(" ")

trnsct_123.total_price()
print(" ")

trnsct_123.check_order()